name: genifer
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip==24.2
  - numpy==1.26.4
  - cudatoolkit==11.1.1
  - pytorch==1.9.1
  - torchvision==0.10.1
  - imageio-ffmpeg==0.4.3
  - scikit-learn==1.5.2
  - tensorboard==2.17.1
  - click==8.1.7
  - requests==2.32.3
  - tqdm==4.66.5
  - ninja==1.12.1
  - seaborn==0.13.2
  - pip:
    - pyspng==0.1.2
    - setuptools==59.5.0
    - mlflow==2.16.1
